:xrefstyle: short
:listing-caption: Listing

// Table of contents is inserted here
toc::[]

:leveloffset: 1

This document is (c) 2021, Khronos Group. Usage and license details are at the end of the document.

[[copyright-license]]
[[copyright]]
[[license]]
= Copyright and License

Copyright 2021, The Khronos Group Inc.
This Document is protected by copyright laws and contains material proprietary to Khronos. Except as described by these terms, it or any components may not be reproduced, republished, distributed, transmitted, displayed, broadcast or otherwise exploited in any manner without the express prior written permission of Khronos.

Khronos grants a conditional copyright license to use and reproduce the unmodified Document for any purpose, without fee or royalty, EXCEPT no licenses to any patent, trademark or other intellectual property rights are granted under these terms.

Khronos makes no, and expressly disclaims any, representations or warranties, express or implied, regarding this Document, including, without limitation: merchantability, fitness for a particular purpose, non-infringement of any intellectual property, correctness, accuracy, completeness, timeliness, and reliability. Under no circumstances will Khronos, or any of its Promoters, Contributors or Members, or their respective partners, officers, directors, employees, agents or representatives be liable for any damages, whether direct, indirect, special or consequential damages for lost revenues, lost profits, or otherwise, arising from or in connection with these materials.

Khronos® and Vulkan® are registered trademarks, and ANARI™, WebGL™, glTF™, NNEF™, OpenVX™, SPIR™, SPIR-V™, SYCL™, OpenVG™ and 3D Commerce™ are trademarks of The Khronos Group Inc. OpenXR™ is a trademark owned by The Khronos Group Inc. and is registered as a trademark in China, the European Union, Japan and the United Kingdom. OpenCL™ is a trademark of Apple Inc. and OpenGL® is a registered trademark and the OpenGL ES™ and OpenGL SC™ logos are trademarks of Hewlett Packard Enterprise used under license by Khronos. ASTC is a trademark of ARM Holdings PLC. All other product names, trademarks, and/or company names are used solely for identification and belong to their respective owners.

The models are copyright by various creators and are licensed as https://creativecommons.org/licenses/by/4.0/[Creative Commons with Attribution 4.0 International (CC-BY 4.0)]

* **AnalyticalCubes:** Copyright 2020, Amazon. 
* **AnalyticalGrayscale:** Copyright 2020, Amazon. 
* **AnalyticalSpheres:** Copyright 2020, Amazon. 
* **Mixer:** Copyright 2020, Shopify. 
* **Shoe:**  Copyright 2020, Shopify. 
* **Wicker Chair:** Copyright 2020, Wayfair LLC. Model and textures by Eric Chadwick.
* **Tennis Raquet:** Copyright 2020, Samsung Research America. Model and textures by Duncan Knarr.
* **Green Chair:** Copyright 2020, IKEA Systems B.V. ("IKEA")

** The data contained in the green_chair.glb (binary) and .gltf files (the "Licensed Material") is licensed by IKEA under the Creative Commons Attribution 4.0
International Public License (CC BY 4.0) for the evaluation and development of an open technology standard for 3D models. The Licensed Material is limited to 3D modelling data/technology and does not include any IKEA products/objects.

** IKEA reserves the exclusive rights to the design, copyright and other intellectual property rights in the Licensed Materials as well as in its products/objects